### ISSUE TITLE
Unable to access the remote server

### ISSUE THREAD

**Issue by Dr-Corgi** [jinzhuoran/CogIE#1]
Hi @jinzhuoran , is the [server](https://github.com/jinzhuoran/CogIE/blob/819f693373fd14f7e804169523e89ffe545bdc2f/cogie/utils/model.py#L11) mentioned in this code still working? It seems that the script was unable to download the trained model via [Line 39](https://github.com/jinzhuoran/CogIE/blob/819f693373fd14f7e804169523e89ffe545bdc2f/cogie/utils/model.py#L39).

**Comment by jinzhuoran** [comment]
Hi, thanks for your interest. The original server is no longer used, we'll provide a new URL soon.

**Comment by Dr-Corgi** [comment]
Thank you very much.

**Comment by jinzhuoran** [comment]
> Thank you very much.

Hi, we have updated the download URL.
Please have a try:)

**Comment by Dr-Corgi** [comment]
> > Thank you very much.
> 
> Hi, we have updated the download URL. Please have a try:)

It works! Thanks a lot!

**Comment by HuXiangkun** [comment]
The server is unreachable again.
