### ISSUE TITLE
数据集中的vocabulary.txt是怎么来的？？

### ISSUE THREAD

**Issue by qinglongheu** [jinzhuoran/CogIE#3]

**Comment by jinzhuoran** [comment]
这是人工构建的词表，实现label到id的映射，可以在这里访问http://210.75.240.140:9999/cogie/models/ner/conll2003/toolkit/vocabulary.txt

**Comment by qinglongheu** [comment]
> 这是人工构建的词表，实现label到id的映射，可以在这里访问http://210.75.240.140:9999/cogie/models/ner/conll2003/toolkit/vocabulary.txt
好的，感谢

**Comment by qinglongheu** [comment]
> 这是人工构建的词表，实现label到id的映射，可以在这里访问http://210.75.240.140:9999/cogie/models/ner/conll2003/toolkit/vocabulary.txt

这个是根据train.txt构建的词表吗？？

**Comment by qinglongheu** [comment]
> 这是人工构建的词表，实现label到id的映射，可以在这里访问http://210.75.240.140:9999/cogie/models/ner/conll2003/toolkit/vocabulary.txt

我从hugging face上下载的数据集，经过你的代码处理后得到的vaculary.txt中的数据格式是下面这样的， 代码报错RuntimeError: encoding_type cannot be inferred automatically. Only support 'bio', 'bmes', 'bmeso', 'bioes' type.
max_size	None
min_freq	None
unknown	<unk>
padding	<pad>
rebuild	False

0]"	1	2	0
10094,['Quarter-finals'],[24],[11],[0]	1	3	0
10097,['4:21.715'],[11],[11],[0]	1	4	0
1010,['*'],[34],[0],[0]	1	5	0
10101,['4:20.241'],[11],[11],[0]	1	6	0
1012,['*'],[34],[0],[0]	1	7	0
1018,['1996-08-22'],[11],[11],[0]	1	8	0
10292,['.'],[7],[0],[0]	1	9	0
10329,['R'],[21],[11],[0]	1	10	0
1035,['1996-08-22'],[11],[11],[0]	1	11	0
10673,['Attendance'],[37],[21],[0]	1	12	0
10693,['Halftime'],[37],[21],[0]	1	13	0
10838,['India'],[22],[11],[5]	1	14	0
10948,['---'],[34],[0],[0]	1	15	0
10974,['1996-08-28'],[11],[11],[0]	1	16	0
10975,['Quarterly'],[16],[11],[0]	1	17	0

**Comment by qinglongheu** [comment]
> 这是人工构建的词表，实现label到id的映射，可以在这里访问http://210.75.240.140:9999/cogie/models/ner/conll2003/toolkit/vocabulary.txt

能提供一下你的原始conll2003吗？hugging face上的数据格式应该和你的不一样，感谢
