### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by ShangQingTu** [jinzhuoran/CogIE#6]
Hi @jinzhuoran , is the [server](https://github.com/jinzhuoran/CogIE/blob/819f693373fd14f7e804169523e89ffe545bdc2f/cogie/utils/model.py#L11) mentioned in this code still working? It seems that the script was unable to download the trained model.
![image](https://user-images.githubusercontent.com/56705394/228851388-e1f867fe-6b90-45da-b384-9bf480073179.png)

**Comment by jinzhuoran** [comment]
Hi @ShangQingTu, thanks for your attention. The problem has been fixed.

**Comment by ShangQingTu** [comment]
Thank you
